### PR TITLE
Align with LilyPond

### PR DESCRIPTION
**Pull request by rettinghaus**
This PR just brings changes from the LilyPond repo over here. 

See https://gitlab.com/lilypond/lilypond/-/commits/master/input/regression/musicxml

### CODE REVIEW

**Review by mscuthbert — APPROVED** [review]
In general in the future, let's update the doctype to the latest musicxml when possible.  I have a good memory, but I can't remember what 0.6beta allows or doesn't allow.  Besides that. THANKS so MUCH!

**Comment by lemzwerg** [comment]
@mscuthbert, @rettinghaus, I just want to chime in and mention that much more changes to the MusicXML test suite will come in the very near future – I'm working right now on a complete overhaul of `musicxml2ly` so that it produces decent results (again), slowly walking over all test files.  As one of the last steps I will also update the MusicXML version signatures everywhere.

As a consequence I suggest to wait with mergers until I've consolidated the test files.  Note that I also actively use this repository as a resource, trying to merge differences as much as I consider useful.  If you find mistakes in my editing actions (in LilyPond's git repository, I mean) please tell me so that I can fix them in due course!

**Comment by rettinghaus** [comment]
@lemzwerg any updates on your work?

**Comment by lemzwerg** [comment]
Working daily on it!  However, it's a huge undertaking, and I'm far from finished yet, sorry.  Most of the descriptions have already improved, and many tests have been extended and/or added.  This is mainly used as a regression test suite for `musicxml2ly`, however, I try to make the tests useful in general.

You might have a look; any comments are welcomed.

**Comment by lemzwerg** [comment]
To see what's tested: Here is a PDF file that shows the description and rendering results of the MusicXML test suite as done with my latest Merge Request from today, https://gitlab.com/lilypond/lilypond/-/merge_requests/2457.  I'm around the files starting with `40`.

[collated-files.pdf](https://github.com/user-attachments/files/17401039/collated-files.pdf)

**Pull request merged**
